# docker-compose.yml
# NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) docker-compose -f ./compose/ws.yml up -d
services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: always
    network_mode: bridge
    mac_address: 02:42:ac:11:00:02  # 添加MAC地址固化配置
    
    ports:
      - 3001:3001
      - 6099:6099
    
    volumes:
      - ./data/napcat/config:/app/napcat/config
      - ./data/ntqq:/app/.config/QQ
  redis:
    image: redis:5
    container_name: napcat-redis
    restart: always
    ports:
      - 6379:6379